version: "3.8"
services:
  tg_dev3:
    image: "xpertmind/tigergraph:free_3.0.5"
    container_name: tg_dev3
    hostname: tg_dev3
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '1022:22'
      - '14240:14240'
    links:
      - kafka:kafka
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ./volume/TigerGraph/data:/var/lib/tigergraph/data
      - ./volume/TigerGraph/scripts:/home/tigergraph/scripts
    stdin_open: true
    tty: true
    networks:
      tg_net:
        ipv4_address: 10.16.33.3

    healthcheck:
            test: ["CMD-SHELL", "curl --fail http://localhost:9000/echo || exit 1"]
            interval: 5s
            timeout: 10s
            retries: 5
  conda:
    image: "xpertmind/tigergraph_conda"
    container_name: conda
    hostname: conda
    ports:
      - '8888:8888'
    restart: unless-stopped
    networks:
      tg_net:
        ipv4_address: 10.16.33.4

  zookeeper:
    image: 'debezium/zookeeper:1.2'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./volume/zookeeper/data:/zookeeper/data
      - ./volume/zookeeper/txns:/zookeeper/txns
    networks:
      tg_net:
        ipv4_address: 10.16.33.5

  kafka:
    image: 'debezium/kafka:1.2'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - BROKER_ID=1
      - ZOOKEEPER_CONNECT=zookeeper
    volumes:
      - ./volume/kafka:/kafka/data
    depends_on:
      - zookeeper
    networks:
      tg_net:
        ipv4_address: 10.16.33.6

  mariadb:
    image: 'mariadb:10.5'
    container_name: mariadb
    hostname: mariadb
    ports:
      - '3306:3306'
    volumes:
      - './volume/MariaDB/data:/var/lib/mysql'
      - './volume/MariaDB/logs:/var/log/mysql'
      - './volume/MariaDB/conf.d:/etc/mysql/conf.d'

    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tgdemo
      MYSQL_USER: tigergraph
      MYSQL_PASSWORD: tigergraph
    restart: on-failure
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10

    networks:
      tg_net:
        ipv4_address: 10.16.33.7

  kafka_connect:
    image: 'debezium/connect:1.2'
    container_name: k_connect
    hostname: k_connect
    ports:
      - '8083:8083'
    depends_on:
      - zookeeper
      - kafka
      - mariadb
    links:
      - mariadb:mariadb
      - kafka:kafka
      - zookeeper:zookeeper
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - BOOTSTRAP_SERVERS=kafka:9092

    volumes:
      - ./volume/k_connect:/kafka/logs
    depends_on:
      - zookeeper
    networks:
      tg_net:
        ipv4_address: 10.16.33.8
    healthcheck:
              test: ["CMD-SHELL", "curl -H 'Accept:application/json' --fail http://localhost:8083 || exit 1"]
              interval: 5s
              timeout: 10s
              retries: 5

networks:
    tg_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.16.33.0/28
