version: "3.8"
services:
  tg3:
    image: "xpertmind/tigergraph:3.3.0"
    container_name: tg3
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '14240:14240'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ./TigerGraph/data:/var/lib/tigergraph/data
      - ./TigerGraph/scripts:/home/tigergraph/scripts
    stdin_open: true
    tty: true
    networks:
      tg_net:
        ipv4_address: 10.16.33.3

    healthcheck:
            test: curl --fail http://localhost:9000/echo
            interval: 5s
            timeout: 10s
            retries: 5

networks:
    tg_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.16.33.0/28
