version: "3.8"
services:
  tgente3:
    image: "xpertmind/tigergraph:latest"
    container_name: tgente3
    restart: unless-stopped
    ports:
      - '9003:9000'
      - '2022:22'
      - '14243:14240'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ./tigergraph/scripts:/home/tigergraph/scripts
      - ./tigergraph/log:/opt/tigergraph/log
      - ./tigergraph/data:/opt/tigergraph/data
    stdin_open: true
    tty: true
    networks:
      tg_net:
        ipv4_address: 10.16.43.2

networks:
    tg_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.16.43.0/28
