version: "3.8"
services:
  lastmin3:
    image: "xpertmind/tigergraph:free_latest"
    container_name: syntheatg3
    hostname: syntheatg3
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '1022:22'
      - '14240:14240'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ./TigerGraph/data:/opt/tigergraph/data
      - ./TigerGraph/scripts:/home/tigergraph/scripts
      - ./TigerGraph/log:/opt/tigergraph/log
    stdin_open: true
    tty: true

    healthcheck:
            test: ["CMD-SHELL", "curl --fail http://localhost:9000/echo || exit 1"]
            interval: 5s
            timeout: 10s
            retries: 5
